name: Docker Build & Publish
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    stpes:
      - name: Clone my repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}" # Login to Docker Hub with secrets
      - name: Construir imagen
        run: docker build -t dairymod115/dockerfundamentals:v2 .
      - name: Publicar imagen 
        run: docker push dairymod115/dockerfundamentals:v2